[INFO -- 2018-11-27 18:03:34]
Starting flip_value script
version: 1.1
[INFO -- 2018-11-27 18:03:34]
Initialization strings:
[INFO -- 2018-11-27 18:03:34]
(1) file /tmp/lreg/lreg
[INFO -- 2018-11-27 18:03:34]
(2) set args /tmp/lreg/randInput /tmp/lreg/output
[INFO -- 2018-11-27 18:03:34]
initSignal:0
[INFO -- 2018-11-27 18:03:34]
endSignal:3
[INFO -- 2018-11-27 18:03:34]
faultModel:1
[EXCEPTION -- 2018-11-27 18:03:36]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-11-27 18:03:36]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[EXCEPTION -- 2018-11-27 18:03:37]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[INFO -- 2018-11-27 18:03:37]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6ec6801 in __GI_abort () at abort.c:79
#2  0x00007ffff6f0f897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff703cb9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6f1690a in malloc_printerr (str=str@entry=0x7ffff703ad88 "free(): invalid pointer") at malloc.c:5350
#4  0x00007ffff6f1de1c in _int_free (have_lock=0, p=0x5555557724f4, av=0x7ffff7271c40 <main_arena>) at malloc.c:4157
#5  __GI___libc_free (mem=0x555555772504) at malloc.c:3124
#6  0x0000555555558018 in __gnu_cxx::new_allocator<double>::deallocate (this=0x7fffffffd720, __p=0x555555772504) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x0000555555557add in std::allocator_traits<std::allocator<double> >::deallocate (__a=..., __p=0x555555772504, __n=6) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x0000555555557230 in std::_Vector_base<double, std::allocator<double> >::_M_deallocate (this=0x7fffffffd720, __p=0x555555772504, __n=6) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x0000555555556eed in std::_Vector_base<double, std::allocator<double> >::~_Vector_base (this=0x7fffffffd720, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x0000555555556919 in std::vector<double, std::allocator<double> >::~vector (this=0x7fffffffd720, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x000055555555709c in std::vector<double, std::allocator<double> >::_M_move_assign (this=0x55555575b180 <T1>, __x=...) at /usr/include/c++/7/bits/stl_vector.h:1531
#12 0x0000555555556971 in std::vector<double, std::allocator<double> >::operator= (this=0x55555575b180 <T1>, __x=...) at /usr/include/c++/7/bits/stl_vector.h:466
#13 0x0000555555555d6e in train (iter1=30000, iter2=30000, N=4, alpha1=2.2222199999999999e-05, alpha2=2.2222199999999999e-05, stopsWhenStable=true) at lreg.cpp:185
#14 0x0000555555556467 in main (argc=3, argv=0x7fffffffde58) at lreg.cpp:253

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Memory content before bitflip:0x800x000x000x000x000x000x000x00
Fault Model: Double bit-flip
base address to flip value: 0x7ffff7273940 
address max offset: 8
Memory content after  bitflip:0x800x000x000x0c0x000x000x000x00
frame name: malloc_printerr
symbol name: global_max_fast
symbol filename: malloc.c
symbol line: 1630
value: 201326720
value address: 0x7ffff7273940 <global_max_fast>
Type: The type is an integer type.
Type sizeof: 8

[INFO -- 2018-11-27 18:03:37]
Fault Injection Successful after 3.6468312740325928s
[INFO -- 2018-11-27 18:03:38]
event type: exit
[EXCEPTION -- 2018-11-27 18:03:38]
exit code: no exit code available
