[INFO -- 2018-11-08 19:01:20]
Starting flip_value script
version: 1.1
[INFO -- 2018-11-08 19:01:20]
Initialization strings:
[INFO -- 2018-11-08 19:01:20]
(1) file /tmp/lreg/lreg
[INFO -- 2018-11-08 19:01:20]
(2) set args /tmp/lreg/randInput /tmp/lreg/output /tmp/lreg/detected.log
[INFO -- 2018-11-08 19:01:20]
initSignal:0
[INFO -- 2018-11-08 19:01:20]
endSignal:10
[INFO -- 2018-11-08 19:01:20]
faultModel:2
[EXCEPTION -- 2018-11-08 19:01:21]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[EXCEPTION -- 2018-11-08 19:01:21]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-11-08 19:01:22]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6ec6801 in __GI_abort () at abort.c:79
#2  0x00007ffff6f0f897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff703cb9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6f1690a in malloc_printerr (str=str@entry=0x7ffff703ad88 "free(): invalid pointer") at malloc.c:5350
#4  0x00007ffff6f1de1c in _int_free (have_lock=0, p=0x5555557726ea, av=0x7ffff7271c40 <main_arena>) at malloc.c:4157
#5  __GI___libc_free (mem=0x5555557726fa) at malloc.c:3124
#6  0x0000555555557cc2 in __gnu_cxx::new_allocator<double>::deallocate (this=0x55555575b160 <y>, __p=0x5555557726fa) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x00005555555574d1 in std::allocator_traits<std::allocator<double> >::deallocate (__a=..., __p=0x5555557726fa, __n=10) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x0000555555556b7c in std::_Vector_base<double, std::allocator<double> >::_M_deallocate (this=0x55555575b160 <y>, __p=0x5555557726fa, __n=10) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x0000555555556ffd in std::vector<double, std::allocator<double> >::_M_realloc_insert<double const&> (this=0x55555575b160 <y>, __position=0, __args#0=@0x7fffffffd690: 999) at /usr/include/c++/7/bits/vector.tcc:448
#10 0x0000555555556756 in std::vector<double, std::allocator<double> >::push_back (this=0x55555575b160 <y>, __x=@0x7fffffffd690: 999) at /usr/include/c++/7/bits/stl_vector.h:948
#11 0x00005555555559e5 in execute (input=0x7fffffffe1f1 "/tmp/lreg/randInput") at lreg.cpp:154
#12 0x0000555555555c60 in main (argc=4, argv=0x7fffffffde48) at lreg.cpp:191

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Fliping a bit of the value pointed by a reference
Memory content before bitflip:0x000x000x000x000x000x380x8f0x40
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffd690
address max offset: 8
Memory content after  bitflip:0xa50xc40xc30x180x2b0x420x960x0a
frame name: std::vector<double, std::allocator<double> >::push_back
symbol name: __x
symbol filename: /usr/include/c++/7/bits/stl_vector.h
symbol line: 939
value: @0x7fffffffd690
value address: 0x7fffffffd690
Type: A reference type.
Type sizeof: 8

[INFO -- 2018-11-08 19:01:22]
Fault Injection Successful after 2.771181344985962s
[INFO -- 2018-11-08 19:01:23]
event type: exit
[EXCEPTION -- 2018-11-08 19:01:23]
exit code: no exit code available
