[INFO -- 2018-11-12 16:49:22]
Starting flip_value script
version: 1.1
[INFO -- 2018-11-12 16:49:22]
Initialization strings:
[INFO -- 2018-11-12 16:49:22]
(1) file /tmp/lreg/lreg
[INFO -- 2018-11-12 16:49:22]
(2) set args /tmp/lreg/randInput /tmp/lreg/output
[INFO -- 2018-11-12 16:49:22]
initSignal:0
[INFO -- 2018-11-12 16:49:22]
endSignal:10
[INFO -- 2018-11-12 16:49:22]
faultModel:1
[EXCEPTION -- 2018-11-12 16:49:26]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[EXCEPTION -- 2018-11-12 16:49:26]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-11-12 16:49:27]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[INFO -- 2018-11-12 16:49:27]
Backtrace BEGIN:
#0  0x00005555555551e9 in verifyUintDup (a=0, b=0) at lreg.cpp:69
#1  0x0000555555555642 in predict (v=-29) at lreg.cpp:112
#2  0x000055555555578f in meanSquaredError () at lreg.cpp:125
#3  0x0000555555555da8 in train (iter1=45000, iter2=45000, N=4, alpha1=2.2222199999999999e-05, alpha2=2.2222199999999999e-05, stopsWhenStable=true) at lreg.cpp:191
#4  0x00005555555562e6 in main (argc=3, argv=0x7fffffffde68) at lreg.cpp:246

64			ofstream fp ("/tmp/lreg/detected.log", std::ofstream::app);
65			fp << "verifyUint: a = "<<a<<"; b = "<<b<<endl;
66	        detected = 1;	
67		}
68		return a;
69	}
70	double verifyDoubleDup(double a, double b){
71		if (a != b && detected != 1){
72			//gerar entrada no log
73			ofstream fp ("/tmp/lreg/detected.log", std::ofstream::app);

Backtrace END
Memory content before bitflip:0x000x000x000x00
Fault Model: Double bit-flip
base address to flip value: 0x7fffffffd764
address max offset: 4
Memory content after  bitflip:0x000x180x000x00
frame name: predict
symbol name: i2
symbol filename: lreg.cpp
symbol line: 112
value: 6144
value address: 0x7fffffffd764
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2018-11-12 16:49:27]
Fault Injection Successful after 5.845814943313599s
[INFO -- 2018-11-12 16:49:45]
event type: exit
[EXCEPTION -- 2018-11-12 16:49:45]
exit code: no exit code available
