[INFO -- 2018-10-03 16:41:43]
Starting flip_value script
version: 1.1
[INFO -- 2018-10-03 16:41:43]
Initialization strings:
[INFO -- 2018-10-03 16:41:43]
(1) file /tmp/lreg/lreg
[INFO -- 2018-10-03 16:41:43]
(2) set args /tmp/lreg/randInput /tmp/lreg/output
[INFO -- 2018-10-03 16:41:43]
initSignal:0
[INFO -- 2018-10-03 16:41:43]
endSignal:10
[INFO -- 2018-10-03 16:41:43]
faultModel:1
[EXCEPTION -- 2018-10-03 16:41:44]
pythonException: empty range for randrange() (0,0, 0)
[EXCEPTION -- 2018-10-03 16:41:44]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-10-03 16:41:44]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6ec1801 in __GI_abort () at abort.c:79
#2  0x00007ffff7ad38fb in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7ad9d3a in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff7ad9d95 in std::terminate() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff7ad9fe8 in __cxa_throw () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007ffff7b02f26 in std::__throw_bad_alloc() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#7  0x00005555555577ca in __gnu_cxx::new_allocator<double>::allocate (this=0x7fffffffd8a0, __n=18446744073709551602) at /usr/include/c++/7/ext/new_allocator.h:102
#8  0x0000555555557563 in std::allocator_traits<std::allocator<double> >::allocate (__a=..., __n=18446744073709551602) at /usr/include/c++/7/bits/alloc_traits.h:436
#9  0x000055555555703a in std::_Vector_base<double, std::allocator<double> >::_M_allocate (this=0x7fffffffd8a0, __n=18446744073709551602) at /usr/include/c++/7/bits/stl_vector.h:172
#10 0x0000555555556d5b in std::_Vector_base<double, std::allocator<double> >::_M_create_storage (this=0x7fffffffd8a0, __n=18446744073709551602) at /usr/include/c++/7/bits/stl_vector.h:187
#11 0x000055555555644b in std::_Vector_base<double, std::allocator<double> >::_Vector_base (this=0x7fffffffd8a0, __n=18446744073709551602, __a=...) at /usr/include/c++/7/bits/stl_vector.h:138
#12 0x0000555555555f1d in std::vector<double, std::allocator<double> >::vector (this=0x7fffffffd8a0, __x=std::vector of length -13, capacity -13 = {...}) at /usr/include/c++/7/bits/stl_vector.h:328
#13 0x00005555555556c3 in train (iterations=60000, alpha=5.0000000000000002e-05, N=3, stopsWhenStable=true) at lreg.cpp:126
#14 0x0000555555555ab7 in main (argc=3, argv=0x7fffffffde58) at lreg.cpp:174

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Memory content before bitflip:0xf20xff0xff0xff0xff0xff0xff0xff
Fault Model: Double bit-flip
base address to flip value: 0x7fffffffd730
address max offset: 8
Memory content after  bitflip:0xf20xff0xff0x7e0xff0xff0xff0xff
frame name: std::_Vector_base<double, std::allocator<double> >::_M_allocate
symbol name: __n
symbol filename: /usr/include/c++/7/bits/stl_vector.h
symbol line: 169
value: 18446744071545290738
value address: 0x7fffffffd730
Type: The type is an integer type.
Type sizeof: 8

[INFO -- 2018-10-03 16:41:44]
Fault Injection Successful after 1.6538798809051514s
[INFO -- 2018-10-03 16:41:44]
event type: exit
[EXCEPTION -- 2018-10-03 16:41:44]
exit code: no exit code available
