[INFO -- 2018-11-12 16:03:06]
Starting flip_value script
version: 1.1
[INFO -- 2018-11-12 16:03:06]
Initialization strings:
[INFO -- 2018-11-12 16:03:06]
(1) file /tmp/lreg/lreg
[INFO -- 2018-11-12 16:03:06]
(2) set args /tmp/lreg/randInput /tmp/lreg/output
[INFO -- 2018-11-12 16:03:06]
initSignal:0
[INFO -- 2018-11-12 16:03:06]
endSignal:10
[INFO -- 2018-11-12 16:03:06]
faultModel:0
[EXCEPTION -- 2018-11-12 16:03:15]
pythonException: empty range for randrange() (0,0, 0)
[INFO -- 2018-11-12 16:03:17]
Backtrace BEGIN:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x00007ffff6ec6801 in __GI_abort () at abort.c:79
#2  0x00007ffff6f0f897 in __libc_message (action=action@entry=do_abort, fmt=fmt@entry=0x7ffff703cb9a "%s\n") at ../sysdeps/posix/libc_fatal.c:181
#3  0x00007ffff6f1690a in malloc_printerr (str=str@entry=0x7ffff703ad88 "free(): invalid pointer") at malloc.c:5350
#4  0x00007ffff6f1de1c in _int_free (have_lock=0, p=0x5555557728a0, av=0x7ffff7271c40 <main_arena>) at malloc.c:4157
#5  __GI___libc_free (mem=0x5555557728b0) at malloc.c:3124
#6  0x0000555555557ea8 in __gnu_cxx::new_allocator<double>::deallocate (this=0x55555575b140 <x>, __p=0x5555557728b0) at /usr/include/c++/7/ext/new_allocator.h:125
#7  0x000055555555796e in std::allocator_traits<std::allocator<double> >::deallocate (__a=..., __p=0x5555557728b0, __n=48) at /usr/include/c++/7/bits/alloc_traits.h:462
#8  0x00005555555570c2 in std::_Vector_base<double, std::allocator<double> >::_M_deallocate (this=0x55555575b140 <x>, __p=0x5555557728b0, __n=48) at /usr/include/c++/7/bits/stl_vector.h:180
#9  0x0000555555556d59 in std::_Vector_base<double, std::allocator<double> >::~_Vector_base (this=0x55555575b140 <x>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:162
#10 0x00005555555567ab in std::vector<double, std::allocator<double> >::~vector (this=0x55555575b140 <x>, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/stl_vector.h:435
#11 0x00007ffff6ec9041 in __run_exit_handlers (status=0, listp=0x7ffff7271718 <__exit_funcs>, run_list_atexit=run_list_atexit@entry=true, run_dtors=run_dtors@entry=true) at exit.c:108
#12 0x00007ffff6ec913a in __GI_exit (status=<optimized out>) at exit.c:139
#13 0x00007ffff6ea7b9e in __libc_start_main (main=0x555555555f65 <main(int, char**)>, argc=3, argv=0x7fffffffde68, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffde58) at ../csu/libc-start.c:344
#14 0x000055555555501a in _start ()

46	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.

Backtrace END
Fliping value of field: __val
Fliping array at pos: 6
Memory content before bitflip:0x700xdb0xff0xff0xff0x7f0x000x00
Fault Model: Single bit-flip
base address to flip value: 0x7fffffffd890
address max offset: 8
Memory content after  bitflip:0x700xdb0xff0xff0xfb0x7f0x000x00
frame name: __GI_raise
symbol name: set
symbol filename: ../sysdeps/unix/sysv/linux/raise.c
symbol line: 39
value: {__val = {0, 0, 140737488346072, 140737348894104, 140737488345968, 140737349154651, 140720308476784, 14236871696962045440, 140737488346208, 140737488346496, 93824992235504, 140737348928561, 0, 93824992240740, 1, 13895668633763315712}}
value address: 0x7fffffffd860
Type: The type is a structure.
Type sizeof: 128
Field name: __val
Field Type: The type is an array.
Field Type sizeof: 128

[INFO -- 2018-11-12 16:03:17]
Fault Injection Successful after 11.2149817943573s
[INFO -- 2018-11-12 16:03:17]
event type: exit
[EXCEPTION -- 2018-11-12 16:03:17]
exit code: no exit code available
