[INFO -- 2018-11-25 16:35:32]
Starting flip_value script
version: 1.1
[INFO -- 2018-11-25 16:35:32]
Initialization strings:
[INFO -- 2018-11-25 16:35:32]
(1) file /tmp/lreg/lreg
[INFO -- 2018-11-25 16:35:32]
(2) set args /tmp/lreg/randInput /tmp/lreg/output /tmp/lreg/detected.log
[INFO -- 2018-11-25 16:35:32]
initSignal:0
[INFO -- 2018-11-25 16:35:32]
endSignal:6
[INFO -- 2018-11-25 16:35:32]
faultModel:2
[EXCEPTION -- 2018-11-25 16:35:34]
pythonException: Unable to exit loop in struct fields; Exiting wihtout making a bit flip
[EXCEPTION -- 2018-11-25 16:35:35]
gdbException: Cannot access memory at address 0x60e1c0fccbf4fa93
[INFO -- 2018-11-25 16:35:36]
Backtrace BEGIN:
#0  0x000055555555638b in std::vector<double, std::allocator<double> >::vector (this=0x7fffffffd5b0, __x=std::vector of length -872622408049081064, capacity -872622408049081064 = {...}) at /usr/include/c++/7/bits/stl_vector.h:326
#1  0x0000555555555713 in train (iterations=10000, alpha=0.00020000000000000001, N=2, stopsWhenStable=true) at lreg.cpp:126
#2  0x0000555555555a1c in execute (input=0x7fffffffe1f1 "/tmp/lreg/randInput") at lreg.cpp:157
#3  0x0000555555555c78 in main (argc=4, argv=0x7fffffffde48) at lreg.cpp:193

321	       *  (i.e. capacity() == size() in the new %vector).
322	       *
323	       *  The newly-created %vector uses a copy of the allocator object used
324	       *  by @a __x (unless the allocator traits dictate a different object).
325	       */
326	      vector(const vector& __x)
327	      : _Base(__x.size(),
328		_Alloc_traits::_S_select_on_copy(__x._M_get_Tp_allocator()))
329	      {
330		this->_M_impl._M_finish =

Backtrace END
Memory content before bitflip:0x040x000x000x00
Fault Model: Random bit-flip
base address to flip value: 0x7fffffffd674
address max offset: 4
Memory content after  bitflip:0x620xe60xf20x01
frame name: execute
symbol name: predictions
symbol filename: lreg.cpp
symbol line: 144
value: 32695906
value address: 0x7fffffffd674
Type: The type is an integer type.
Type sizeof: 4

[INFO -- 2018-11-25 16:35:36]
Fault Injection Successful after 4.301560401916504s
[INFO -- 2018-11-25 16:35:36]
event type: exit
[EXCEPTION -- 2018-11-25 16:35:36]
exit code: no exit code available
